# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeChallenge.io
description: CodeChallenge.io is the go to place for people of any skill, to improve their coding/programming abilities. We provide projects and challenges for you to complete, show off and learn a ton from.
url: "http://codechallenge.io/" # the base hostname & protocol for your site
